# Generated by Django 4.1.2 on 2023-05-23 11:38

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='debugg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='guide',
            fields=[
                ('guide_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=20)),
                ('guide_name', models.CharField(max_length=50)),
                ('guide_email', models.EmailField(max_length=20)),
                ('teams', django_mysql.models.ListCharField(models.CharField(default='', max_length=100), default='', max_length=10000, size=10)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(default='hee', max_length=20)),
                ('team_std_div', models.CharField(max_length=10)),
                ('team_no', models.CharField(default='', max_length=2)),
                ('mem1', models.CharField(default=' ', max_length=10)),
                ('mem2', models.CharField(default=' ', max_length=10)),
                ('mem3', models.CharField(default=' ', max_length=10)),
                ('mem4', models.CharField(default=' ', max_length=10)),
                ('project_name', models.CharField(default=' ', max_length=10)),
                ('guide', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project_connector_app.guide')),
            ],
        ),
    ]
