# Generated by Django 4.1.2 on 2023-05-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_connector_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
