# Generated by Django 4.1.2 on 2023-05-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_connector_app', '0002_alter_team_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='teams',
        ),
    ]
