# Generated by Django 4.1.2 on 2023-05-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_connector_app', '0003_remove_guide_teams'),
    ]

    operations = [
        migrations.DeleteModel(
            name='debugg',
        ),
    ]
