# Generated by Django 4.1.2 on 2023-05-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_connector_app', '0004_delete_debugg'),
    ]

    operations = [
        migrations.CreateModel(
            name='updates_by_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('work_name', models.CharField(default='', max_length=50)),
                ('work_des', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
