# Generated by Django 4.1.2 on 2023-06-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_connector_app', '0006_updates_by_team_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updates_by_team',
            name='guide',
        ),
    ]
