# Generated by Django 4.1.2 on 2023-06-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_connector_app', '0009_updates_by_team_team_std_div'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_assign_by_guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('team_std_div', models.CharField(default='', max_length=10)),
                ('team_no', models.CharField(default='', max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('work_name', models.CharField(default='', max_length=50)),
                ('work_des', models.CharField(default='', max_length=50)),
                ('guide', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project_connector_app.guide')),
            ],
        ),
    ]
